name: Issues Automation

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_RAD_CI_BOT_PAT }}
    steps:
      - name: Add label if author in preview team
        env:
          ISSUE: ${{ github.event.issue.html_url }}
          AUTHOR: ${{ github.event.issue.user }}
        run: |
          MEMBERS=$(gh api orgs/project-radius/teams/Radius-Preview/members | jq -r '.[] | .login')
          for USER in $MEMBERS; do
            if [[ "$USER" == "$AUTHOR" ]]; then
              echo "Adding label for issue $ISSUE"
              gh issue edit $ISSUE --add-label "customer-issue"
            fi
          done
